language: java
jdk:
    -openjdk8    
  
addons:
  apt:
    packages:
      - openjfx
  sonarcloud:
    organization: "effibot"
    token: 
      secure: "tWYITJ+pOJXMEzWBEgKABKS7DAihyvgSus7fXDQLS95D2Visv3Spjo5GCgXh72f9djiq7Kk+OoLd4q+hVK75CyfqnIiEdb97E7XFbWY3+ZZNNlYGEsRFJCp5xORqmPi0KNO3ys0CZiBz2+7NarLRaX0XHqKW9TgrAhaGsCe7KHmHWJWq5ZD0zwhnLPx8UpFYYxrtWH3VTE5TF52AXkE5Mt/bEOLHOlqzdrnuvXG+c6oM4bKgEfjiR8N8t+MJfBvKLo0i9ByqqXNtxwBpRRQV/lZLguJLvKR0vl09zcyD2BBxYU34G4eIyiTGpFyRJQlRiMk3WOy9Eq9Pw4wUpkxC0nmvnOBbSa0y8SRdgJRkf9gr0zx1GmrgiRU7xv54XJWL/d90W4knIkLv8lYaQSrAag1DWPADZGjlF32zusRGY2oxYy74gtry1nYKR/3SXVRbQoyQpY+sBNoZZn6APicIHybp/mWFn2yx7TLv09dIXfE8qe5A2e1CXWYI9WvVAwk3NX5o9zXgzaiMjtbOAZYDbgrWUzownYH6RTNoNLcl8L+HQMGWk++N0PmnkSy43pwLk7vtmgrF7m8DGvYkhEgcdpE53ytFQqmG1/ee82/4FmOx1mJph7NrL/WLHvB4ztDBtQXmbd/bPisQX+b1/E4F1DLssGc4WTK6wPbVefypA0I="

script: 
- ant build
- sonar-scanner

